### ISSUE TITLE
Doesn't support copying max quantity of selected item

### ISSUE THREAD

**Issue by takispanag** [cpieprzak/PoeAggregator#21]
For example i have a search for The Doctor card for 1ex, and the guy has 2 The Doctor cards. I want to be able to pm for 2 cards for the price of 2 ex. Is this possible?

**Comment by cpieprzak** [comment]
Hm.  I'm thinking maybe a slider that shows up if quantity is present.

**Comment by takispanag** [comment]
For my use case i want max quantity if thats possible. And you can have the slider too.

**Comment by akaAMAZING** [comment]
I second this feature, would be very useful - especially to buy bulk currency for crafting at a better rate than the regular bulk sellers you can find.

For example, if I need 'x' essences for crafting - I currently have two options:

1. Pay the bulk market price (which usually start from at least 2x what a single essence would sell for)
2. Purchase them one by one as the trade site is clunky when it comes to buying in bulk with live searches.

Perhaps instead of a slider, we can specify the minimum quantity? So it wouldn't alert me for single essence listings but if there are 5 listed from the same seller for the regular price that one goes for, it would alert me.

Hopefully that makes sense!

Thank you!

**Comment by cpieprzak** [comment]
https://github.com/cpieprzak/PoeAggregator/releases/tag/v4.5.0

**Comment by akaAMAZING** [comment]
Looks good! Couple of issues though.

1. If you specific 1 min quantity, it doesn't send an alert when 1 of that item is listed. 

Example: I send an alert for Ancient Orb at 17c specifying 1 as minimum quantity as I wanted the tool to offer for higher amounts of quantity too. However, while it does alert for anything over 1, it does not alert when only 1 is listed.

2. Regarding the PM-ing over 1, isn't it possible to modify the regular string instead of adding it in asterisks?

Example:
Current: Hi, I would like to buy your Ancient Orb listed for 17 chaos in Scourge (stash tab "For Sale"; position: left 3, top 5).                                                                                                      **********************  3 Ancient Orb for  51 chaos   **********************
Revised: Hi, I would like to buy your 3 Ancient Orbs listed for 51 chaos in Scourge (stash tab "For Sale"; position: left 3, top 5).

Thank you for your efforts!

**Comment by cpieprzak** [comment]
Message changes were already in the works.
https://github.com/cpieprzak/PoeAggregator/releases/tag/v4.5.2
Specifying a quant of 1 will send the normal message ( and show 1 quant trades).

Changing the original string is possible, but not really feasible because of all the languages that poe supports.

**Comment by akaAMAZING** [comment]
Yeah I supposed you're right - it would just have been a cool QoL though as it's how the Bulk Exchange area would display it + people may have an affinity towards those as it shows the message into their trade tool with the correct numbers already. Especially when they're getting spammed, they're more likely to look at the trade tool and sell to the higher quantity requester as opposed to looking into chat.

However, really appreciate the great work!! Keep it up!! Thank you! <3

**Comment by cpieprzak** [comment]
Closing issue.  This appears solved.
